# Generated by Django 5.0.7 on 2024-07-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_marca_alter_producto_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='description',
        ),
    ]
