# Generated by Django 5.0.7 on 2024-07-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
    ]
